;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2022/10/18/星期二 下午 02:43:11

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1003	1003	; add | Microsoft Learn add.htm
#define IDH_1001	1001	; add alias | Microsoft Learn add-alias.htm
#define IDH_1004	1004	; append | Microsoft Learn append.htm
#define IDH_1005	1005	; arp | Microsoft Learn arp.htm
#define IDH_1006	1006	; assign | Microsoft Learn assign.htm
#define IDH_1007	1007	; assoc | Microsoft Learn assoc.htm
#define IDH_1002	1002	; add volume | Microsoft Learn add-volume.htm
#define IDH_1008	1008	; at | Microsoft Learn at.htm
#define IDH_1009	1009	; atmadm | Microsoft Learn atmadm.htm
#define IDH_1011	1011	; attrib | Microsoft Learn attrib.htm
#define IDH_1014	1014	; attributes | Microsoft Learn attributes.htm
#define IDH_1012	1012	; attributes disk | Microsoft Learn attributes-disk.htm
#define IDH_1013	1013	; attributes volume | Microsoft Learn attributes-volume.htm
#define IDH_1023	1023	; auditpol | Microsoft Learn auditpol.htm
#define IDH_1015	1015	; auditpol backup | Microsoft Learn auditpol-backup.htm
#define IDH_1016	1016	; auditpol clear | Microsoft Learn auditpol-clear.htm
#define IDH_1017	1017	; auditpol get | Microsoft Learn auditpol-get.htm
#define IDH_1018	1018	; auditpol list | Microsoft Learn auditpol-list.htm
#define IDH_1019	1019	; auditpol remove | Microsoft Learn auditpol-remove.htm
#define IDH_1020	1020	; auditpol resourceSACL | Microsoft Learn auditpol-resourcesacl.htm
#define IDH_1021	1021	; auditpol restore | Microsoft Learn auditpol-restore.htm
#define IDH_1022	1022	; auditpol set | Microsoft Learn auditpol-set.htm
#define IDH_1024	1024	; autochk | Microsoft Learn autochk.htm
#define IDH_1025	1025	; autoconv | Microsoft Learn autoconv.htm
#define IDH_1026	1026	; autofmt | Microsoft Learn autofmt.htm
#define IDH_1027	1027	; automount | Microsoft Learn automount.htm
#define IDH_1028	1028	; bcdboot | Microsoft Learn bcdboot.htm
#define IDH_1029	1029	; bcdedit | Microsoft Learn bcdedit.htm
#define IDH_1036	1036	; bdehdcfg | Microsoft Learn bdehdcfg.htm
#define IDH_1030	1030	; bdehdcfg driveinfo | Microsoft Learn bdehdcfg-driveinfo.htm
#define IDH_1031	1031	; bdehdcfg newdriveletter | Microsoft Learn bdehdcfg-newdriveletter.htm
#define IDH_1032	1032	; bdehdcfg quiet | Microsoft Learn bdehdcfg-quiet.htm
#define IDH_1033	1033	; bdehdcfg restart | Microsoft Learn bdehdcfg-restart.htm
#define IDH_1034	1034	; bdehdcfg size | Microsoft Learn bdehdcfg-size.htm
#define IDH_1035	1035	; bdehdcfg target | Microsoft Learn bdehdcfg-target.htm
#define IDH_1037	1037	; begin backup | Microsoft Learn begin-backup.htm
#define IDH_1038	1038	; begin restore | Microsoft Learn begin-restore.htm
#define IDH_1148	1148	; bitsadmin | Microsoft Learn bitsadmin.htm
#define IDH_1039	1039	; bitsadmin addfile | Microsoft Learn bitsadmin-addfile.htm
#define IDH_1040	1040	; bitsadmin addfileset | Microsoft Learn bitsadmin-addfileset.htm
#define IDH_1041	1041	; bitsadmin addfilewithranges | Microsoft Learn bitsadmin-addfilewithranges.htm
#define IDH_1052	1052	; bitsadmin cache | Microsoft Learn bitsadmin-cache.htm
#define IDH_1051	1051	; bitsadmin cache 和 clear | Microsoft Learn bitsadmin-cache-clear.htm
#define IDH_1042	1042	; bitsadmin cache 和 delete | Microsoft Learn bitsadmin-cache-and-delete.htm
#define IDH_1043	1043	; bitsadmin cache 和 deleteURL | Microsoft Learn bitsadmin-cache-and-deleteurl.htm
#define IDH_1044	1044	; bitsadmin cache 和 getexpirationtime | Microsoft Learn bitsadmin-cache-and-getexpirationtime.htm
#define IDH_1045	1045	; bitsadmin cache 和 getlimit | Microsoft Learn bitsadmin-cache-and-getlimit.htm
#define IDH_1046	1046	; bitsadmin cache 和 help | Microsoft Learn bitsadmin-cache-and-help.htm
#define IDH_1047	1047	; bitsadmin cache 和 info | Microsoft Learn bitsadmin-cache-and-info.htm
#define IDH_1048	1048	; bitsadmin cache 和 list | Microsoft Learn bitsadmin-cache-and-list.htm
#define IDH_1049	1049	; bitsadmin cache 和 setexpirationtime | Microsoft Learn bitsadmin-cache-and-setexpirationtime.htm
#define IDH_1050	1050	; bitsadmin cache 和 setlimit | Microsoft Learn bitsadmin-cache-and-setlimit.htm
#define IDH_1053	1053	; bitsadmin cancel | Microsoft Learn bitsadmin-cancel.htm
#define IDH_1054	1054	; bitsadmin complete | Microsoft Learn bitsadmin-complete.htm
#define IDH_1055	1055	; bitsadmin create | Microsoft Learn bitsadmin-create.htm
#define IDH_1057	1057	; bitsadmin getaclflags | Microsoft Learn bitsadmin-getaclflags.htm
#define IDH_1058	1058	; bitsadmin getbytestotal | Microsoft Learn bitsadmin-getbytestotal.htm
#define IDH_1059	1059	; bitsadmin getbytestransferred | Microsoft Learn bitsadmin-getbytestransferred.htm
#define IDH_1060	1060	; bitsadmin getclientcertificate | Microsoft Learn bitsadmin-getclientcertificate.htm
#define IDH_1061	1061	; bitsadmin getcompletiontime | Microsoft Learn bitsadmin-getcompletiontime.htm
#define IDH_1062	1062	; bitsadmin getcreationtime | Microsoft Learn bitsadmin-getcreationtime.htm
#define IDH_1063	1063	; bitsadmin getcustomheaders | Microsoft Learn bitsadmin-getcustomheaders.htm
#define IDH_1064	1064	; bitsadmin getdescription | Microsoft Learn bitsadmin-getdescription.htm
#define IDH_1065	1065	; bitsadmin getdisplayname | Microsoft Learn bitsadmin-getdisplayname.htm
#define IDH_1066	1066	; bitsadmin geterror | Microsoft Learn bitsadmin-geterror.htm
#define IDH_1067	1067	; bitsadmin geterrorcount | Microsoft Learn bitsadmin-geterrorcount.htm
#define IDH_1068	1068	; bitsadmin getfilestotal | Microsoft Learn bitsadmin-getfilestotal.htm
#define IDH_1069	1069	; bitsadmin getfilestransferred | Microsoft Learn bitsadmin-getfilestransferred.htm
#define IDH_1070	1070	; bitsadmin gethelpertokenflags | Microsoft Learn bitsadmin-gethelpertokenflags.htm
#define IDH_1071	1071	; bitsadmin gethelpertokensid | Microsoft Learn bitsadmin-gethelpertokensid.htm
#define IDH_1072	1072	; bitsadmin gethttpmethod | Microsoft Learn bitsadmin-gethttpmethod.htm
#define IDH_1073	1073	; bitsadmin getmaxdownloadtime | Microsoft Learn bitsadmin-getmaxdownloadtime.htm
#define IDH_1074	1074	; bitsadmin getminretrydelay | Microsoft Learn bitsadmin-getminretrydelay.htm
#define IDH_1075	1075	; bitsadmin getmodificationtime | Microsoft Learn bitsadmin-getmodificationtime.htm
#define IDH_1076	1076	; bitsadmin getnoprogresstimeout | Microsoft Learn bitsadmin-getnoprogresstimeout.htm
#define IDH_1077	1077	; bitsadmin getnotifycmdline | Microsoft Learn bitsadmin-getnotifycmdline.htm
#define IDH_1078	1078	; bitsadmin getnotifyflags | Microsoft Learn bitsadmin-getnotifyflags.htm
#define IDH_1079	1079	; bitsadmin getnotifyinterface | Microsoft Learn bitsadmin-getnotifyinterface.htm
#define IDH_1080	1080	; bitsadmin getowner | Microsoft Learn bitsadmin-getowner.htm
#define IDH_1081	1081	; bitsadmin getpeercachingflags | Microsoft Learn bitsadmin-getpeercachingflags.htm
#define IDH_1082	1082	; bitsadmin getpriority | Microsoft Learn bitsadmin-getpriority.htm
#define IDH_1083	1083	; bitsadmin getproxybypasslist | Microsoft Learn bitsadmin-getproxybypasslist.htm
#define IDH_1084	1084	; bitsadmin getproxylist - 检索指定作业的代理列表。 | Microsoft Learn bitsadmin-getproxylist.htm
#define IDH_1085	1085	; bitsadmin getproxyusage | Microsoft Learn bitsadmin-getproxyusage.htm
#define IDH_1086	1086	; bitsadmin getreplydata | Microsoft Learn bitsadmin-getreplydata.htm
#define IDH_1087	1087	; bitsadmin getreplyfilename | Microsoft Learn bitsadmin-getreplyfilename.htm
#define IDH_1088	1088	; bitsadmin getreplyprogress | Microsoft Learn bitsadmin-getreplyprogress.htm
#define IDH_1089	1089	; bitsadmin getsecurityflags | Microsoft Learn bitsadmin-getsecurityflags.htm
#define IDH_1090	1090	; bitsadmin getstate | Microsoft Learn bitsadmin-getstate.htm
#define IDH_1091	1091	; bitsadmin gettemporaryname | Microsoft Learn bitsadmin-gettemporaryname.htm
#define IDH_1092	1092	; bitsadmin gettype | Microsoft Learn bitsadmin-gettype.htm
#define IDH_1093	1093	; bitsadmin getvalidationstate | Microsoft Learn bitsadmin-getvalidationstate.htm
#define IDH_1094	1094	; bitsadmin help | Microsoft Learn bitsadmin-help.htm
#define IDH_1095	1095	; bitsadmin info | Microsoft Learn bitsadmin-info.htm
#define IDH_1096	1096	; bitsadmin list | Microsoft Learn bitsadmin-list.htm
#define IDH_1097	1097	; bitsadmin listfiles | Microsoft Learn bitsadmin-listfiles.htm
#define IDH_1098	1098	; bitsadmin makecustomheaderswriteonly | Microsoft Learn bitsadmin-makecustomheaderswriteonly.htm
#define IDH_1099	1099	; bitsadmin monitor | Microsoft Learn bitsadmin-monitor.htm
#define IDH_1100	1100	; bitsadmin nowrap | Microsoft Learn bitsadmin-nowrap.htm
#define IDH_1104	1104	; bitsadmin peercaching | Microsoft Learn bitsadmin-peercaching.htm
#define IDH_1101	1101	; bitsadmin peercaching 和 getconfigurationflags | Microsoft Learn bitsadmin-peercaching-and-getconfigurationflags.htm
#define IDH_1102	1102	; bitsadmin peercaching 和 help | Microsoft Learn bitsadmin-peercaching-and-help.htm
#define IDH_1103	1103	; bitsadmin peercaching 和 setconfigurationflags | Microsoft Learn bitsadmin-peercaching-and-setconfigurationflags.htm
#define IDH_1109	1109	; bitsadmin peers | Microsoft Learn bitsadmin-peers.htm
#define IDH_1105	1105	; bitsadmin peers 和 clear | Microsoft Learn bitsadmin-peers-and-clear.htm
#define IDH_1106	1106	; bitsadmin peers 和 discover | Microsoft Learn bitsadmin-peers-and-discover.htm
#define IDH_1107	1107	; bitsadmin peers 和 help | Microsoft Learn bitsadmin-peers-and-help.htm
#define IDH_1108	1108	; bitsadmin peers 和 list | Microsoft Learn bitsadmin-peers-and-list.htm
#define IDH_1110	1110	; bitsadmin rawreturn | Microsoft Learn bitsadmin-rawreturn.htm
#define IDH_1111	1111	; bitsadmin removeclientcertificate | Microsoft Learn bitsadmin-removeclientcertificate.htm
#define IDH_1112	1112	; bitsadmin removecredentials | Microsoft Learn bitsadmin-removecredentials.htm
#define IDH_1113	1113	; bitsadmin replaceremoteprefix | Microsoft Learn bitsadmin-replaceremoteprefix.htm
#define IDH_1114	1114	; bitsadmin reset | Microsoft Learn bitsadmin-reset.htm
#define IDH_1115	1115	; bitsadmin resume | Microsoft Learn bitsadmin-resume.htm
#define IDH_1116	1116	; bitsadmin setaclflag | Microsoft Learn bitsadmin-setaclflag.htm
#define IDH_1117	1117	; bitsadmin setclientcertificatebyid | Microsoft Learn bitsadmin-setclientcertificatebyid.htm
#define IDH_1118	1118	; bitsadmin setclientcertificatebyname | Microsoft Learn bitsadmin-setclientcertificatebyname.htm
#define IDH_1119	1119	; bitsadmin setcredentials | Microsoft Learn bitsadmin-setcredentials.htm
#define IDH_1120	1120	; bitsadmin setcustomheaders | Microsoft Learn bitsadmin-setcustomheaders.htm
#define IDH_1121	1121	; bitsadmin setdescription | Microsoft Learn bitsadmin-setdescription.htm
#define IDH_1122	1122	; bitsadmin setdisplayname | Microsoft Learn bitsadmin-setdisplayname.htm
#define IDH_1123	1123	; bitsadmin sethelpertoken | Microsoft Learn bitsadmin-sethelpertoken.htm
#define IDH_1124	1124	; bitsadmin sethelpertokenflags | Microsoft Learn bitsadmin-sethelpertokenflags.htm
#define IDH_1125	1125	; bitsadmin sethttpmethod | Microsoft Learn bitsadmin-sethttpmethod.htm
#define IDH_1126	1126	; bitsadmin setmaxdownloadtime | Microsoft Learn bitsadmin-setmaxdownloadtime.htm
#define IDH_1127	1127	; bitsadmin setminretrydelay | Microsoft Learn bitsadmin-setminretrydelay.htm
#define IDH_1128	1128	; bitsadmin setnoprogresstimeout | Microsoft Learn bitsadmin-setnoprogresstimeout.htm
#define IDH_1129	1129	; bitsadmin setnotifycmdline | Microsoft Learn bitsadmin-setnotifycmdline.htm
#define IDH_1130	1130	; bitsadmin setnotifyflags | Microsoft Learn bitsadmin-setnotifyflags.htm
#define IDH_1131	1131	; bitsadmin setpeercachingflags | Microsoft Learn bitsadmin-setpeercachingflags.htm
#define IDH_1132	1132	; bitsadmin setpriority | Microsoft Learn bitsadmin-setpriority.htm
#define IDH_1133	1133	; bitsadmin setproxysettings | Microsoft Learn bitsadmin-setproxysettings.htm
#define IDH_1134	1134	; bitsadmin setreplyfilename | Microsoft Learn bitsadmin-setreplyfilename.htm
#define IDH_1135	1135	; bitsadmin setsecurityflags | Microsoft Learn bitsadmin-setsecurityflags.htm
#define IDH_1136	1136	; bitsadmin setvalidationstate | Microsoft Learn bitsadmin-setvalidationstate.htm
#define IDH_1137	1137	; bitsadmin suspend | Microsoft Learn bitsadmin-suspend.htm
#define IDH_1138	1138	; bitsadmin takeownership | Microsoft Learn bitsadmin-takeownership.htm
#define IDH_1139	1139	; bitsadmin transfer | Microsoft Learn bitsadmin-transfer.htm
#define IDH_1146	1146	; bitsadmin util | Microsoft Learn bitsadmin-util.htm
#define IDH_1140	1140	; bitsadmin util 和 enableanalyticchannel | Microsoft Learn bitsadmin-util-and-enableanalyticchannel.htm
#define IDH_1141	1141	; bitsadmin util 和 getieproxy | Microsoft Learn bitsadmin-util-and-getieproxy.htm
#define IDH_1142	1142	; bitsadmin util 和 help | Microsoft Learn bitsadmin-util-and-help.htm
#define IDH_1143	1143	; bitsadmin util 和 repairservice | Microsoft Learn bitsadmin-util-and-repairservice.htm
#define IDH_1144	1144	; bitsadmin util 和 setieproxy | Microsoft Learn bitsadmin-util-and-setieproxy.htm
#define IDH_1145	1145	; bitsadmin util 和 version | Microsoft Learn bitsadmin-util-and-version.htm
#define IDH_1147	1147	; bitsadmin wrap | Microsoft Learn bitsadmin-wrap.htm
#define IDH_1056	1056	; bitsadmin 示例 | Microsoft Learn bitsadmin-examples.htm
#define IDH_1160	1160	; bootcfg | Microsoft Learn bootcfg.htm
#define IDH_1149	1149	; bootcfg addsw | Microsoft Learn bootcfg-addsw.htm
#define IDH_1150	1150	; bootcfg copy | Microsoft Learn bootcfg-copy.htm
#define IDH_1151	1151	; bootcfg dbg1394 | Microsoft Learn bootcfg-dbg1394.htm
#define IDH_1152	1152	; bootcfg debug | Microsoft Learn bootcfg-debug.htm
#define IDH_1153	1153	; bootcfg default | Microsoft Learn bootcfg-default.htm
#define IDH_1154	1154	; bootcfg delete | Microsoft Learn bootcfg-delete.htm
#define IDH_1155	1155	; bootcfg ems | Microsoft Learn bootcfg-ems.htm
#define IDH_1156	1156	; bootcfg query | Microsoft Learn bootcfg-query.htm
#define IDH_1157	1157	; bootcfg raw | Microsoft Learn bootcfg-raw.htm
#define IDH_1158	1158	; bootcfg rmsw | Microsoft Learn bootcfg-rmsw.htm
#define IDH_1159	1159	; bootcfg timeout | Microsoft Learn bootcfg-timeout.htm
#define IDH_1161	1161	; break | Microsoft Learn break.htm
#define IDH_1163	1163	; cacls | Microsoft Learn cacls.htm
#define IDH_1164	1164	; call | Microsoft Learn call.htm
#define IDH_1165	1165	; CD | Microsoft Learn cd.htm
#define IDH_1166	1166	; certreq | Microsoft Learn certreq_1.htm
#define IDH_1167	1167	; certutil | Microsoft Learn certutil.htm
#define IDH_1168	1168	; change logon | Microsoft Learn change-logon.htm
#define IDH_1169	1169	; change port | Microsoft Learn change-port.htm
#define IDH_1170	1170	; change user | Microsoft Learn change-user.htm
#define IDH_1172	1172	; chcp | Microsoft Learn chcp.htm
#define IDH_1173	1173	; chdir | Microsoft Learn chdir.htm
#define IDH_1174	1174	; chglogon | Microsoft Learn chglogon.htm
#define IDH_1175	1175	; chgport | Microsoft Learn chgport.htm
#define IDH_1176	1176	; chgusr | Microsoft Learn chgusr.htm
#define IDH_1177	1177	; chkdsk | Microsoft Learn chkdsk.htm
#define IDH_1178	1178	; chkntfs | Microsoft Learn chkntfs.htm
#define IDH_1179	1179	; choice | Microsoft Learn choice.htm
#define IDH_1180	1180	; cipher | Microsoft Learn cipher.htm
#define IDH_1181	1181	; clean | Microsoft Learn clean.htm
#define IDH_1182	1182	; cleanmgr | Microsoft Learn cleanmgr.htm
#define IDH_1183	1183	; clip | Microsoft Learn clip.htm
#define IDH_1184	1184	; cls | Microsoft Learn cls.htm
#define IDH_1185	1185	; cmd | Microsoft Learn cmd.htm
#define IDH_1186	1186	; cmdkey | Microsoft Learn cmdkey.htm
#define IDH_1187	1187	; cmstp | Microsoft Learn cmstp.htm
#define IDH_1188	1188	; color | Microsoft Learn color.htm
#define IDH_1190	1190	; comp | Microsoft Learn comp.htm
#define IDH_1192	1192	; compact | Microsoft Learn compact.htm
#define IDH_1191	1191	; compact vdisk | Microsoft Learn compact-vdisk.htm
#define IDH_1197	1197	; convert | Microsoft Learn convert.htm
#define IDH_1193	1193	; convert basic | Microsoft Learn convert-basic.htm
#define IDH_1194	1194	; convert dynamic | Microsoft Learn convert-dynamic.htm
#define IDH_1195	1195	; convert gpt | Microsoft Learn convert-gpt.htm
#define IDH_1196	1196	; convert mbr | Microsoft Learn convert-mbr.htm
#define IDH_1720	1720	; convert-riprepimage | Microsoft Learn wdsutil-convert-riprepimage.htm
#define IDH_1198	1198	; copy | Microsoft Learn copy.htm
#define IDH_1721	1721	; copy-drivergroup | Microsoft Learn wdsutil-copy-drivergroup.htm
#define IDH_1199	1199	; cprofile | Microsoft Learn cprofile.htm
#define IDH_1209	1209	; create | Microsoft Learn create.htm
#define IDH_1200	1200	; create partition efi | Microsoft Learn create-partition-efi.htm
#define IDH_1201	1201	; create partition extended | Microsoft Learn create-partition-extended.htm
#define IDH_1202	1202	; create partition logical | Microsoft Learn create-partition-logical.htm
#define IDH_1203	1203	; create partition msr | Microsoft Learn create-partition-msr.htm
#define IDH_1204	1204	; create partition primary | Microsoft Learn create-partition-primary.htm
#define IDH_1205	1205	; create volume mirror | Microsoft Learn create-volume-mirror.htm
#define IDH_1206	1206	; create volume raid | Microsoft Learn create-volume-raid.htm
#define IDH_1207	1207	; create volume simple | Microsoft Learn create-volume-simple.htm
#define IDH_1208	1208	; create volume stripe | Microsoft Learn create-volume-stripe.htm
#define IDH_1210	1210	; cscript | Microsoft Learn cscript.htm
#define IDH_1211	1211	; date | Microsoft Learn date.htm
#define IDH_1212	1212	; dcgpofix | Microsoft Learn dcgpofix.htm
#define IDH_1213	1213	; defrag | Microsoft Learn defrag.htm
#define IDH_1214	1214	; del | Microsoft Learn del.htm
#define IDH_1219	1219	; delete | Microsoft Learn delete.htm
#define IDH_1215	1215	; delete disk | Microsoft Learn delete-disk.htm
#define IDH_1216	1216	; delete partition | Microsoft Learn delete-partition.htm
#define IDH_1217	1217	; delete shadows | Microsoft Learn delete-shadows.htm
#define IDH_1218	1218	; delete volume | Microsoft Learn delete-volume.htm
#define IDH_1220	1220	; detach vdisk | Microsoft Learn detach-vdisk.htm
#define IDH_1221	1221	; detail disk | Microsoft Learn detail-disk.htm
#define IDH_1222	1222	; detail partition | Microsoft Learn detail-partition.htm
#define IDH_1223	1223	; detail vdisk | Microsoft Learn detail-vdisk.htm
#define IDH_1224	1224	; detail volume | Microsoft Learn detail-volume.htm
#define IDH_1231	1231	; dfsdiag | Microsoft Learn dfsdiag.htm
#define IDH_1226	1226	; dfsdiag testdcs | Microsoft Learn dfsdiag-testdcs.htm
#define IDH_1227	1227	; dfsdiag testdfsconfig | Microsoft Learn dfsdiag-testdfsconfig.htm
#define IDH_1228	1228	; dfsdiag testdfsintegrity | Microsoft Learn dfsdiag-testdfsintegrity.htm
#define IDH_1229	1229	; dfsdiag testreferral | Microsoft Learn dfsdiag-testreferral.htm
#define IDH_1230	1230	; dfsdiag testsites | Microsoft Learn dfsdiag-testsites.htm
#define IDH_1232	1232	; dfsrmig | Microsoft Learn dfsrmig.htm
#define IDH_1233	1233	; diantz | Microsoft Learn diantz.htm
#define IDH_1234	1234	; dir | Microsoft Learn dir.htm
#define IDH_1235	1235	; diskcomp | Microsoft Learn diskcomp.htm
#define IDH_1236	1236	; diskcopy | Microsoft Learn diskcopy.htm
#define IDH_1237	1237	; diskpart | Microsoft Learn diskpart.htm
#define IDH_1238	1238	; diskperf | Microsoft Learn diskperf.htm
#define IDH_1239	1239	; Diskraid | Microsoft Learn diskraid.htm
#define IDH_1240	1240	; Diskshadow | Microsoft Learn diskshadow.htm
#define IDH_1241	1241	; dispdiag | Microsoft Learn dispdiag.htm
#define IDH_1242	1242	; dnscmd | Microsoft Learn dnscmd.htm
#define IDH_1243	1243	; doskey | Microsoft Learn doskey.htm
#define IDH_1710	1710	; DriverGroupFilter | Microsoft Learn wdsutil-add-drivergroupfilter.htm
#define IDH_1713	1713	; DriverPackage | Microsoft Learn wdsutil-add-driverpackage.htm
#define IDH_1744	1744	; DriverPackage | Microsoft Learn wdsutil-get-driverpackage.htm
#define IDH_1244	1244	; driverquery | Microsoft Learn driverquery.htm
#define IDH_1245	1245	; echo | Microsoft Learn echo.htm
#define IDH_1248	1248	; end restore | Microsoft Learn end-restore.htm
#define IDH_1249	1249	; endlocal | Microsoft Learn endlocal.htm
#define IDH_1250	1250	; erase | Microsoft Learn erase.htm
#define IDH_1251	1251	; eventcreate | Microsoft Learn eventcreate.htm
#define IDH_1252	1252	; eventquery | Microsoft Learn eventquery.htm
#define IDH_1253	1253	; eventtriggers | Microsoft Learn eventtriggers.htm
#define IDH_1254	1254	; evntcmd | Microsoft Learn evntcmd.htm
#define IDH_1255	1255	; exec | Microsoft Learn exec.htm
#define IDH_1256	1256	; exit | Microsoft Learn exit.htm
#define IDH_1258	1258	; expand | Microsoft Learn expand.htm
#define IDH_1257	1257	; expand vdisk | Microsoft Learn expand-vdisk.htm
#define IDH_1259	1259	; expose | Microsoft Learn expose.htm
#define IDH_1260	1260	; extend | Microsoft Learn extend.htm
#define IDH_1261	1261	; extract | Microsoft Learn extract.htm
#define IDH_1262	1262	; fc | Microsoft Learn fc.htm
#define IDH_1263	1263	; filesystems | Microsoft Learn filesystems.htm
#define IDH_1264	1264	; find | Microsoft Learn find.htm
#define IDH_1265	1265	; findstr | Microsoft Learn findstr.htm
#define IDH_1266	1266	; finger | Microsoft Learn finger.htm
#define IDH_1267	1267	; flattemp | Microsoft Learn flattemp.htm
#define IDH_1270	1270	; forfiles | Microsoft Learn forfiles.htm
#define IDH_1271	1271	; format | Microsoft Learn format.htm
#define IDH_1272	1272	; freedisk | Microsoft Learn freedisk.htm
#define IDH_1273	1273	; fsutil 8dot3name | Microsoft Learn fsutil-8dot3name.htm
#define IDH_1290	1290	; fsutil | Microsoft Learn fsutil.htm
#define IDH_1274	1274	; fsutil behavior | Microsoft Learn fsutil-behavior.htm
#define IDH_1275	1275	; fsutil dirty | Microsoft Learn fsutil-dirty.htm
#define IDH_1276	1276	; fsutil file | Microsoft Learn fsutil-file.htm
#define IDH_1277	1277	; Fsutil fsinfo | Microsoft Learn fsutil-fsinfo.htm
#define IDH_1278	1278	; fsutil hardlink | Microsoft Learn fsutil-hardlink.htm
#define IDH_1279	1279	; fsutil objectid | Microsoft Learn fsutil-objectid.htm
#define IDH_1280	1280	; fsutil quota | Microsoft Learn fsutil-quota.htm
#define IDH_1281	1281	; fsutil repair | Microsoft Learn fsutil-repair.htm
#define IDH_1282	1282	; fsutil reparsepoint | Microsoft Learn fsutil-reparsepoint.htm
#define IDH_1283	1283	; fsutil resource | Microsoft Learn fsutil-resource.htm
#define IDH_1284	1284	; fsutil sparse | Microsoft Learn fsutil-sparse.htm
#define IDH_1285	1285	; fsutil tiering | Microsoft Learn fsutil-tiering.htm
#define IDH_1286	1286	; fsutil transaction | Microsoft Learn fsutil-transaction.htm
#define IDH_1287	1287	; fsutil usn | Microsoft Learn fsutil-usn.htm
#define IDH_1288	1288	; fsutil volume | Microsoft Learn fsutil-volume.htm
#define IDH_1289	1289	; fsutil wim | Microsoft Learn fsutil-wim.htm
#define IDH_1328	1328	; ftp | Microsoft Learn ftp.htm
#define IDH_1291	1291	; ftp append | Microsoft Learn ftp-append.htm
#define IDH_1292	1292	; ftp ascii | Microsoft Learn ftp-ascii.htm
#define IDH_1293	1293	; ftp bell | Microsoft Learn ftp-bell_1.htm
#define IDH_1294	1294	; ftp binary | Microsoft Learn ftp-binary.htm
#define IDH_1295	1295	; ftp bye | Microsoft Learn ftp-bye.htm
#define IDH_1296	1296	; ftp cd | Microsoft Learn ftp-cd.htm
#define IDH_1297	1297	; ftp close | Microsoft Learn ftp-close_1.htm
#define IDH_1298	1298	; ftp debug | Microsoft Learn ftp-debug.htm
#define IDH_1299	1299	; ftp delete | Microsoft Learn ftp-delete.htm
#define IDH_1300	1300	; ftp dir | Microsoft Learn ftp-dir.htm
#define IDH_1301	1301	; ftp disconnect | Microsoft Learn ftp-disconnect_1.htm
#define IDH_1302	1302	; ftp get | Microsoft Learn ftp-get.htm
#define IDH_1303	1303	; ftp glob | Microsoft Learn ftp-glob_1.htm
#define IDH_1304	1304	; ftp hash | Microsoft Learn ftp-hash_1.htm
#define IDH_1305	1305	; ftp lcd | Microsoft Learn ftp-lcd.htm
#define IDH_1306	1306	; ftp literal | Microsoft Learn ftp-literal_1.htm
#define IDH_1307	1307	; ftp ls | Microsoft Learn ftp-ls_1.htm
#define IDH_1329	1329	; ftp mdelete | Microsoft Learn ftp.mdelete_1.htm
#define IDH_1330	1330	; ftp mdir | Microsoft Learn ftp.mdir.htm
#define IDH_1308	1308	; ftp mget | Microsoft Learn ftp-mget.htm
#define IDH_1309	1309	; ftp mkdir | Microsoft Learn ftp-mkdir.htm
#define IDH_1310	1310	; ftp mls | Microsoft Learn ftp-mls_1.htm
#define IDH_1311	1311	; ftp mput | Microsoft Learn ftp-mput_1.htm
#define IDH_1312	1312	; ftp open | Microsoft Learn ftp-open_1.htm
#define IDH_1313	1313	; ftp prompt | Microsoft Learn ftp-prompt_1.htm
#define IDH_1314	1314	; ftp put | Microsoft Learn ftp-put.htm
#define IDH_1315	1315	; ftp pwd | Microsoft Learn ftp-pwd_1.htm
#define IDH_1316	1316	; ftp quit | Microsoft Learn ftp-quit.htm
#define IDH_1317	1317	; ftp quote | Microsoft Learn ftp-quote.htm
#define IDH_1318	1318	; ftp recv | Microsoft Learn ftp-recv.htm
#define IDH_1319	1319	; ftp remotehelp | Microsoft Learn ftp-remotehelp_1.htm
#define IDH_1320	1320	; ftp rename | Microsoft Learn ftp-rename.htm
#define IDH_1321	1321	; ftp rmdir | Microsoft Learn ftp-rmdir.htm
#define IDH_1322	1322	; ftp send | Microsoft Learn ftp-send_1.htm
#define IDH_1323	1323	; ftp status | Microsoft Learn ftp-status.htm
#define IDH_1324	1324	; ftp trace | Microsoft Learn ftp-trace_1.htm
#define IDH_1325	1325	; ftp type | Microsoft Learn ftp-type.htm
#define IDH_1326	1326	; ftp user | Microsoft Learn ftp-user.htm
#define IDH_1327	1327	; ftp verbose | Microsoft Learn ftp-verbose_1.htm
#define IDH_1331	1331	; ftype | Microsoft Learn ftype.htm
#define IDH_1332	1332	; fveupdate | Microsoft Learn fveupdate.htm
#define IDH_1740	1740	; get-AllServers | Microsoft Learn wdsutil-get-allservers.htm
#define IDH_1747	1747	; get-ImageFile | Microsoft Learn wdsutil-get-imagefile.htm
#define IDH_1333	1333	; getmac | Microsoft Learn getmac.htm
#define IDH_1334	1334	; gettype | Microsoft Learn gettype.htm
#define IDH_1335	1335	; goto | Microsoft Learn goto.htm
#define IDH_1336	1336	; gpfixup | Microsoft Learn gpfixup.htm
#define IDH_1337	1337	; gpresult | Microsoft Learn gpresult.htm
#define IDH_1338	1338	; gpt | Microsoft Learn gpt.htm
#define IDH_1339	1339	; gpupdate | Microsoft Learn gpupdate.htm
#define IDH_1340	1340	; graftabl | Microsoft Learn graftabl.htm
#define IDH_1341	1341	; help | Microsoft Learn help.htm
#define IDH_1342	1342	; helpctr | Microsoft Learn helpctr.htm
#define IDH_1343	1343	; hostname | Microsoft Learn hostname.htm
#define IDH_1344	1344	; icacls | Microsoft Learn icacls.htm
#define IDH_1345	1345	; if | Microsoft Learn if.htm
#define IDH_1347	1347	; import diskpart | Microsoft Learn import_1.htm
#define IDH_1349	1349	; inuse | Microsoft Learn inuse.htm
#define IDH_1350	1350	; ipconfig | Microsoft Learn ipconfig.htm
#define IDH_1351	1351	; ipxroute | Microsoft Learn ipxroute.htm
#define IDH_1352	1352	; irftp | Microsoft Learn irftp.htm
#define IDH_1353	1353	; jetpack | Microsoft Learn jetpack.htm
#define IDH_1354	1354	; klist | Microsoft Learn klist.htm
#define IDH_1377	1377	; ksetup | Microsoft Learn ksetup.htm
#define IDH_1355	1355	; ksetup addenctypeattr | Microsoft Learn ksetup-addenctypeattr.htm
#define IDH_1356	1356	; ksetup addhosttorealmmap | Microsoft Learn ksetup-addhosttorealmmap.htm
#define IDH_1357	1357	; ksetup addkdc | Microsoft Learn ksetup-addkdc.htm
#define IDH_1358	1358	; ksetup addkpasswd | Microsoft Learn ksetup-addkpasswd.htm
#define IDH_1359	1359	; ksetup addrealmflags | Microsoft Learn ksetup-addrealmflags.htm
#define IDH_1360	1360	; ksetup changepassword | Microsoft Learn ksetup-changepassword.htm
#define IDH_1361	1361	; ksetup delenctypeattr | Microsoft Learn ksetup-delenctypeattr.htm
#define IDH_1362	1362	; ksetup delhosttorealmmap | Microsoft Learn ksetup-delhosttorealmmap.htm
#define IDH_1363	1363	; ksetup delkdc | Microsoft Learn ksetup-delkdc.htm
#define IDH_1364	1364	; ksetup delkpasswd | Microsoft Learn ksetup-delkpasswd.htm
#define IDH_1365	1365	; ksetup delrealmflags | Microsoft Learn ksetup-delrealmflags.htm
#define IDH_1366	1366	; ksetup domain | Microsoft Learn ksetup-domain.htm
#define IDH_1367	1367	; ksetup dumpstate | Microsoft Learn ksetup-dumpstate.htm
#define IDH_1368	1368	; ksetup getenctypeattr | Microsoft Learn ksetup-getenctypeattr.htm
#define IDH_1369	1369	; ksetup listrealmflags | Microsoft Learn ksetup-listrealmflags.htm
#define IDH_1370	1370	; ksetup mapuser | Microsoft Learn ksetup-mapuser.htm
#define IDH_1371	1371	; ksetup removerealm | Microsoft Learn ksetup-removerealm.htm
#define IDH_1372	1372	; ksetup server | Microsoft Learn ksetup-server.htm
#define IDH_1373	1373	; ksetup setcomputerpassword | Microsoft Learn ksetup-setcomputerpassword.htm
#define IDH_1374	1374	; ksetup setenctypeattr | Microsoft Learn ksetup-setenctypeattr.htm
#define IDH_1375	1375	; ksetup setrealm | Microsoft Learn ksetup-setrealm.htm
#define IDH_1376	1376	; ksetup setrealmflags | Microsoft Learn ksetup-setrealmflags.htm
#define IDH_1378	1378	; ktmutil | Microsoft Learn ktmutil.htm
#define IDH_1379	1379	; ktpass | Microsoft Learn ktpass.htm
#define IDH_1380	1380	; label | Microsoft Learn label.htm
#define IDH_1385	1385	; list | Microsoft Learn list.htm
#define IDH_1381	1381	; list providers | Microsoft Learn list-providers.htm
#define IDH_1382	1382	; list shadows | Microsoft Learn list-shadows.htm
#define IDH_1383	1383	; list volume | Microsoft Learn list-volume.htm
#define IDH_1384	1384	; list writers | Microsoft Learn list-writers.htm
#define IDH_1386	1386	; load metadata | Microsoft Learn load-metadata.htm
#define IDH_1387	1387	; lodctr | Microsoft Learn lodctr.htm
#define IDH_1404	1404	; logman | Microsoft Learn logman.htm
#define IDH_1393	1393	; logman create | Microsoft Learn logman-create.htm
#define IDH_1388	1388	; logman create alert | Microsoft Learn logman-create-alert.htm
#define IDH_1389	1389	; logman create api | Microsoft Learn logman-create-api.htm
#define IDH_1390	1390	; logman create cfg | Microsoft Learn logman-create-cfg.htm
#define IDH_1391	1391	; logman create counter | Microsoft Learn logman-create-counter.htm
#define IDH_1392	1392	; logman create trace | Microsoft Learn logman-create-trace.htm
#define IDH_1394	1394	; logman delete | Microsoft Learn logman-delete.htm
#define IDH_1395	1395	; logman import and logman export | Microsoft Learn logman-import-export.htm
#define IDH_1396	1396	; logman query | Microsoft Learn logman-query.htm
#define IDH_1397	1397	; logman start and logman stop | Microsoft Learn logman-start-stop.htm
#define IDH_1403	1403	; logman update | Microsoft Learn logman-update.htm
#define IDH_1398	1398	; logman update alert | Microsoft Learn logman-update-alert.htm
#define IDH_1399	1399	; logman update api | Microsoft Learn logman-update-api.htm
#define IDH_1400	1400	; logman update cfg | Microsoft Learn logman-update-cfg.htm
#define IDH_1401	1401	; logman update counter | Microsoft Learn logman-update-counter.htm
#define IDH_1402	1402	; logman update trace | Microsoft Learn logman-update-trace.htm
#define IDH_1406	1406	; lpq | Microsoft Learn lpq.htm
#define IDH_1407	1407	; lpr | Microsoft Learn lpr.htm
#define IDH_1408	1408	; macfile | Microsoft Learn macfile.htm
#define IDH_1409	1409	; makecab | Microsoft Learn makecab.htm
#define IDH_1428	1428	; manage-bde | Microsoft Learn manage-bde.htm
#define IDH_1410	1410	; manage-bde autounlock | Microsoft Learn manage-bde-autounlock.htm
#define IDH_1411	1411	; manage-bde changekey | Microsoft Learn manage-bde-changekey.htm
#define IDH_1412	1412	; manage-bde changepassword | Microsoft Learn manage-bde-changepassword.htm
#define IDH_1413	1413	; manage-bde changepin | Microsoft Learn manage-bde-changepin.htm
#define IDH_1414	1414	; manage-bde forcerecovery | Microsoft Learn manage-bde-forcerecovery.htm
#define IDH_1415	1415	; manage-bde keypackage | Microsoft Learn manage-bde-keypackage.htm
#define IDH_1416	1416	; manage-bde lock | Microsoft Learn manage-bde-lock.htm
#define IDH_1417	1417	; manage-bde off | Microsoft Learn manage-bde-off.htm
#define IDH_1418	1418	; manage-bde on | Microsoft Learn manage-bde-on.htm
#define IDH_1421	1421	; manage-bde resume | Microsoft Learn manage-bde-resume.htm
#define IDH_1422	1422	; manage-bde setidentifier | Microsoft Learn manage-bde-setidentifier.htm
#define IDH_1423	1423	; manage-bde status | Microsoft Learn manage-bde-status.htm
#define IDH_1424	1424	; manage-bde tpm | Microsoft Learn manage-bde-tpm.htm
#define IDH_1425	1425	; manage-bde unlock | Microsoft Learn manage-bde-unlock.htm
#define IDH_1427	1427	; manage-bde wipefreespace | Microsoft Learn manage-bde-wipefreespace.htm
#define IDH_1420	1420	; manage-bde 保护程序 | Microsoft Learn manage-bde-protectors.htm
#define IDH_1426	1426	; manage-bde 升级 | Microsoft Learn manage-bde-upgrade.htm
#define IDH_1419	1419	; manage-bde-暂停 | Microsoft Learn manage-bde-pause.htm
#define IDH_1429	1429	; mapadmin | Microsoft Learn mapadmin.htm
#define IDH_1431	1431	; md | Microsoft Learn md.htm
#define IDH_1432	1432	; merge vdisk | Microsoft Learn merge-vdisk.htm
#define IDH_1433	1433	; mkdir | Microsoft Learn mkdir.htm
#define IDH_1434	1434	; mklink | Microsoft Learn mklink.htm
#define IDH_1435	1435	; mmc | Microsoft Learn mmc.htm
#define IDH_1436	1436	; mode | Microsoft Learn mode.htm
#define IDH_1438	1438	; mount | Microsoft Learn mount.htm
#define IDH_1439	1439	; mountvol | Microsoft Learn mountvol.htm
#define IDH_1441	1441	; mqbkup | Microsoft Learn mqbkup.htm
#define IDH_1442	1442	; mqsvc | Microsoft Learn mqsvc.htm
#define IDH_1443	1443	; mqtgsvc | Microsoft Learn mqtgsvc.htm
#define IDH_1444	1444	; msdt | Microsoft Learn msdt.htm
#define IDH_1445	1445	; msg | Microsoft Learn msg.htm
#define IDH_1446	1446	; msiexec | Microsoft Learn msiexec.htm
#define IDH_1447	1447	; msinfo32 | Microsoft Learn msinfo32.htm
#define IDH_1448	1448	; mstsc | Microsoft Learn mstsc.htm
#define IDH_1449	1449	; nbtstat | Microsoft Learn nbtstat.htm
#define IDH_1450	1450	; net print | Microsoft Learn net-print.htm
#define IDH_1451	1451	; netcfg | Microsoft Learn netcfg.htm
#define IDH_1452	1452	; netsh | Microsoft Learn netsh.htm
#define IDH_1453	1453	; netstat | Microsoft Learn netstat.htm
#define IDH_1755	1755	; new-CaptureImage | Microsoft Learn wdsutil-new-captureimage.htm
#define IDH_1756	1756	; new-DiscoverImage | Microsoft Learn wdsutil-new-discoverimage.htm
#define IDH_1454	1454	; nfsadmin | Microsoft Learn nfsadmin.htm
#define IDH_1455	1455	; nfsshare | Microsoft Learn nfsshare.htm
#define IDH_1456	1456	; nfsstat | Microsoft Learn nfsstat.htm
#define IDH_1457	1457	; nlbmgr | Microsoft Learn nlbmgr.htm
#define IDH_1482	1482	; nslookup | Microsoft Learn nslookup.htm
#define IDH_1459	1459	; nslookup finger | Microsoft Learn nslookup-finger-command.htm
#define IDH_1460	1460	; nslookup help | Microsoft Learn nslookup-help.htm
#define IDH_1461	1461	; nslookup ls | Microsoft Learn nslookup-ls.htm
#define IDH_1462	1462	; nslookup lserver | Microsoft Learn nslookup-lserver.htm
#define IDH_1463	1463	; nslookup root | Microsoft Learn nslookup-root.htm
#define IDH_1464	1464	; nslookup server | Microsoft Learn nslookup-server.htm
#define IDH_1480	1480	; nslookup set | Microsoft Learn nslookup-set.htm
#define IDH_1465	1465	; nslookup set all | Microsoft Learn nslookup-set-all.htm
#define IDH_1466	1466	; nslookup set class | Microsoft Learn nslookup-set-class.htm
#define IDH_1467	1467	; nslookup set d2 | Microsoft Learn nslookup-set-d2.htm
#define IDH_1468	1468	; nslookup set debug | Microsoft Learn nslookup-set-debug.htm
#define IDH_1469	1469	; nslookup set domain | Microsoft Learn nslookup-set-domain.htm
#define IDH_1470	1470	; nslookup set port | Microsoft Learn nslookup-set-port.htm
#define IDH_1471	1471	; nslookup set querytype | Microsoft Learn nslookup-set-querytype.htm
#define IDH_1472	1472	; nslookup set recurse | Microsoft Learn nslookup-set-recurse.htm
#define IDH_1473	1473	; nslookup set retry | Microsoft Learn nslookup-set-retry.htm
#define IDH_1474	1474	; nslookup set root | Microsoft Learn nslookup-set-root.htm
#define IDH_1475	1475	; nslookup set search | Microsoft Learn nslookup-set-search.htm
#define IDH_1476	1476	; nslookup set srchlist | Microsoft Learn nslookup-set-srchlist.htm
#define IDH_1477	1477	; nslookup set timeout | Microsoft Learn nslookup-set-timeout.htm
#define IDH_1478	1478	; nslookup set type | Microsoft Learn nslookup-set-type.htm
#define IDH_1479	1479	; nslookup set vc | Microsoft Learn nslookup-set-vc.htm
#define IDH_1481	1481	; nslookup view | Microsoft Learn nslookup-view.htm
#define IDH_1458	1458	; nslookup 退出 | Microsoft Learn nslookup-exit-command.htm
#define IDH_1483	1483	; ntbackup | Microsoft Learn ntbackup.htm
#define IDH_1484	1484	; ntcmdprompt | Microsoft Learn ntcmdprompt.htm
#define IDH_1485	1485	; ntfrsutl | Microsoft Learn ntfrsutl.htm
#define IDH_1488	1488	; offline | Microsoft Learn offline.htm
#define IDH_1486	1486	; offline disk | Microsoft Learn offline-disk.htm
#define IDH_1487	1487	; offline volume | Microsoft Learn offline-volume.htm
#define IDH_1489	1489	; online disk | Microsoft Learn online-disk.htm
#define IDH_1490	1490	; online volume | Microsoft Learn online-volume.htm
#define IDH_1492	1492	; openfiles | Microsoft Learn openfiles.htm
#define IDH_1493	1493	; pagefileconfig | Microsoft Learn pagefileconfig.htm
#define IDH_1494	1494	; path | Microsoft Learn path.htm
#define IDH_1495	1495	; pathping | Microsoft Learn pathping.htm
#define IDH_1496	1496	; pause | Microsoft Learn pause.htm
#define IDH_1497	1497	; pbadmin | Microsoft Learn pbadmin.htm
#define IDH_1498	1498	; pentnt | Microsoft Learn pentnt.htm
#define IDH_1499	1499	; perfmon | Microsoft Learn perfmon.htm
#define IDH_1500	1500	; ping | Microsoft Learn ping.htm
#define IDH_1512	1512	; pktmon | Microsoft Learn pktmon.htm
#define IDH_1501	1501	; pktmon counters | Microsoft Learn pktmon-counters.htm
#define IDH_1502	1502	; pktmon etl2pcap | Microsoft Learn pktmon-etl2pcap.htm
#define IDH_1503	1503	; pktmon etl2txt | Microsoft Learn pktmon-etl2txt.htm
#define IDH_1505	1505	; pktmon filter | Microsoft Learn pktmon-filter.htm
#define IDH_1504	1504	; pktmon filter add | Microsoft Learn pktmon-filter-add.htm
#define IDH_1506	1506	; pktmon hex2pkt | Microsoft Learn pktmon-hex2pkt.htm
#define IDH_1507	1507	; pktmon list | Microsoft Learn pktmon-list.htm
#define IDH_1508	1508	; pktmon reset | Microsoft Learn pktmon-reset.htm
#define IDH_1509	1509	; pktmon start | Microsoft Learn pktmon-start.htm
#define IDH_1510	1510	; pktmon status | Microsoft Learn pktmon-status.htm
#define IDH_1511	1511	; pktmon unload | Microsoft Learn pktmon-unload.htm
#define IDH_1513	1513	; pnpunattend | Microsoft Learn pnpunattend.htm
#define IDH_1514	1514	; pnputil | Microsoft Learn pnputil.htm
#define IDH_1515	1515	; popd | Microsoft Learn popd.htm
#define IDH_1516	1516	; PowerShell | Microsoft Learn powershell.htm
#define IDH_1517	1517	; PowerShell ise | Microsoft Learn powershell_ise.htm
#define IDH_1519	1519	; print | Microsoft Learn print.htm
#define IDH_1520	1520	; prncnfg | Microsoft Learn prncnfg.htm
#define IDH_1521	1521	; prndrvr | Microsoft Learn prndrvr.htm
#define IDH_1522	1522	; prnjobs | Microsoft Learn prnjobs.htm
#define IDH_1523	1523	; prnmngr | Microsoft Learn prnmngr.htm
#define IDH_1524	1524	; prnport | Microsoft Learn prnport.htm
#define IDH_1525	1525	; prnqctl | Microsoft Learn prnqctl.htm
#define IDH_1526	1526	; prompt | Microsoft Learn prompt.htm
#define IDH_1527	1527	; pubprn | Microsoft Learn pubprn.htm
#define IDH_1528	1528	; pushd | Microsoft Learn pushd.htm
#define IDH_1529	1529	; pushprinterconnections | Microsoft Learn pushprinterconnections.htm
#define IDH_1530	1530	; pwlauncher | Microsoft Learn pwlauncher.htm
#define IDH_1531	1531	; qappsrv | Microsoft Learn qappsrv.htm
#define IDH_1532	1532	; qprocess | Microsoft Learn qprocess.htm
#define IDH_1534	1534	; query session | Microsoft Learn query-session.htm
#define IDH_1535	1535	; query termserver | Microsoft Learn query-termserver.htm
#define IDH_1536	1536	; query user | Microsoft Learn query-user.htm
#define IDH_1538	1538	; quser | Microsoft Learn quser.htm
#define IDH_1539	1539	; qwinsta | Microsoft Learn qwinsta.htm
#define IDH_1540	1540	; rcp | Microsoft Learn rcp.htm
#define IDH_1541	1541	; rd | Microsoft Learn rd.htm
#define IDH_1542	1542	; rdpsign | Microsoft Learn rdpsign.htm
#define IDH_1543	1543	; recover | Microsoft Learn recover.htm
#define IDH_1545	1545	; ReFSUtil | Microsoft Learn refsutil.htm
#define IDH_1546	1546	; reg add | Microsoft Learn reg-add.htm
#define IDH_1547	1547	; reg compare | Microsoft Learn reg-compare.htm
#define IDH_1548	1548	; reg copy | Microsoft Learn reg-copy.htm
#define IDH_1549	1549	; reg delete | Microsoft Learn reg-delete.htm
#define IDH_1550	1550	; reg export | Microsoft Learn reg-export.htm
#define IDH_1551	1551	; reg import | Microsoft Learn reg-import.htm
#define IDH_1552	1552	; reg load | Microsoft Learn reg-load.htm
#define IDH_1553	1553	; reg query | Microsoft Learn reg-query.htm
#define IDH_1554	1554	; reg restore | Microsoft Learn reg-restore.htm
#define IDH_1555	1555	; reg save | Microsoft Learn reg-save.htm
#define IDH_1556	1556	; reg unload | Microsoft Learn reg-unload.htm
#define IDH_1557	1557	; reg 命令 | Microsoft Learn reg.htm
#define IDH_1558	1558	; regini | Microsoft Learn regini.htm
#define IDH_1559	1559	; regsvr32 | Microsoft Learn regsvr32.htm
#define IDH_1560	1560	; relog | Microsoft Learn relog.htm
#define IDH_1561	1561	; rem | Microsoft Learn rem.htm
#define IDH_1762	1762	; remove-DriverGroup | Microsoft Learn wdsutil-remove-drivergroup.htm
#define IDH_1763	1763	; remove-DriverGroupFilter | Microsoft Learn wdsutil-remove-drivergroupfilter.htm
#define IDH_1764	1764	; remove-DriverGroupPackage | Microsoft Learn wdsutil-remove-drivergrouppackage.htm
#define IDH_1564	1564	; ren | Microsoft Learn ren.htm
#define IDH_1566	1566	; repair-bde | Microsoft Learn repair-bde.htm
#define IDH_1568	1568	; replace | Microsoft Learn replace.htm
#define IDH_1571	1571	; reset | Microsoft Learn reset.htm
#define IDH_1570	1570	; reset session | Microsoft Learn reset-session.htm
#define IDH_1572	1572	; retain | Microsoft Learn retain.htm
#define IDH_1573	1573	; revert | Microsoft Learn revert.htm
#define IDH_1574	1574	; rexec | Microsoft Learn rexec.htm
#define IDH_1575	1575	; risetup | Microsoft Learn risetup.htm
#define IDH_1576	1576	; rmdir | Microsoft Learn rmdir.htm
#define IDH_1577	1577	; robocopy | Microsoft Learn robocopy.htm
#define IDH_1579	1579	; rpcinfo | Microsoft Learn rpcinfo.htm
#define IDH_1580	1580	; rpcping | Microsoft Learn rpcping.htm
#define IDH_1581	1581	; rsh | Microsoft Learn rsh.htm
#define IDH_1583	1583	; rundll32 | Microsoft Learn rundll32.htm
#define IDH_1582	1582	; rundll32 printui.dll，PrintUIEntry | Microsoft Learn rundll32-printui.htm
#define IDH_1584	1584	; rwinsta | Microsoft Learn rwinsta.htm
#define IDH_1585	1585	; san | Microsoft Learn san.htm
#define IDH_1586	1586	; sc.exe 配置 | Microsoft Learn sc-config.htm
#define IDH_1589	1589	; Sc.exe查询 | Microsoft Learn sc-query.htm
#define IDH_1587	1587	; sc.exe创建 | Microsoft Learn sc-create.htm
#define IDH_1588	1588	; sc.exe删除 | Microsoft Learn sc-delete.htm
#define IDH_1590	1590	; schtasks delete | Microsoft Learn schtasks-delete.htm
#define IDH_1591	1591	; schtasks end | Microsoft Learn schtasks-end.htm
#define IDH_1592	1592	; schtasks 查询 | Microsoft Learn schtasks-query.htm
#define IDH_1594	1594	; schtasks 命令 | Microsoft Learn schtasks.htm
#define IDH_1593	1593	; schtasks 运行 | Microsoft Learn schtasks-run.htm
#define IDH_1601	1601	; scwcmd | Microsoft Learn scwcmd.htm
#define IDH_1595	1595	; scwcmd analyze | Microsoft Learn scwcmd-analyze.htm
#define IDH_1596	1596	; scwcmd configure | Microsoft Learn scwcmd-configure.htm
#define IDH_1597	1597	; scwcmd register | Microsoft Learn scwcmd-register.htm
#define IDH_1598	1598	; scwcmd rollback | Microsoft Learn scwcmd-rollback.htm
#define IDH_1599	1599	; scwcmd transform | Microsoft Learn scwcmd-transform.htm
#define IDH_1600	1600	; scwcmd view | Microsoft Learn scwcmd-view.htm
#define IDH_1602	1602	; secedit analyze | Microsoft Learn secedit-analyze.htm
#define IDH_1603	1603	; secedit configure | Microsoft Learn secedit-configure.htm
#define IDH_1604	1604	; secedit export | Microsoft Learn secedit-export.htm
#define IDH_1605	1605	; secedit generaterollback | Microsoft Learn secedit-generaterollback.htm
#define IDH_1606	1606	; secedit import | Microsoft Learn secedit-import.htm
#define IDH_1607	1607	; secedit validate | Microsoft Learn secedit-validate.htm
#define IDH_1608	1608	; secedit 命令 | Microsoft Learn secedit.htm
#define IDH_1609	1609	; select disk | Microsoft Learn select-disk.htm
#define IDH_1610	1610	; select partition | Microsoft Learn select-partition.htm
#define IDH_1611	1611	; select vdisk | Microsoft Learn select-vdisk.htm
#define IDH_1612	1612	; select volume | Microsoft Learn select-volume.htm
#define IDH_1613	1613	; select 命令 | Microsoft Learn select.htm
#define IDH_1614	1614	; serverceipoptin | Microsoft Learn serverceipoptin.htm
#define IDH_1615	1615	; servermanagercmd | Microsoft Learn servermanagercmd.htm
#define IDH_1616	1616	; serverweroptin | Microsoft Learn serverweroptin.htm
#define IDH_1626	1626	; set | Microsoft Learn set_1.htm
#define IDH_1619	1619	; set id | Microsoft Learn set-id.htm
#define IDH_1620	1620	; set metadata | Microsoft Learn set-metadata.htm
#define IDH_1621	1621	; set option | Microsoft Learn set-option.htm
#define IDH_1622	1622	; set verbose | Microsoft Learn set-verbose.htm
#define IDH_1623	1623	; set 命令 | Microsoft Learn set.htm
#define IDH_1624	1624	; setlocal | Microsoft Learn setlocal.htm
#define IDH_1625	1625	; setx | Microsoft Learn setx.htm
#define IDH_1627	1627	; sfc | Microsoft Learn sfc.htm
#define IDH_1628	1628	; shadow | Microsoft Learn shadow.htm
#define IDH_1629	1629	; shift | Microsoft Learn shift.htm
#define IDH_1630	1630	; showmount | Microsoft Learn showmount.htm
#define IDH_1632	1632	; shutdown | Microsoft Learn shutdown.htm
#define IDH_1633	1633	; simulate restore | Microsoft Learn simulate-restore.htm
#define IDH_1634	1634	; sort | Microsoft Learn sort.htm
#define IDH_1635	1635	; start | Microsoft Learn start.htm
#define IDH_1775	1775	; Subcommand set-DriverGroup | Microsoft Learn wdsutil-set-drivergroup.htm
#define IDH_1776	1776	; Subcommand set-DriverGroupFilter | Microsoft Learn wdsutil-set-drivergroupfilter.htm
#define IDH_1777	1777	; Subcommand set-DriverPackage | Microsoft Learn wdsutil-set-driverpackage.htm
#define IDH_1636	1636	; subst | Microsoft Learn subst.htm
#define IDH_1637	1637	; sxstrace | Microsoft Learn sxstrace.htm
#define IDH_1638	1638	; sysocmgr | Microsoft Learn sysocmgr.htm
#define IDH_1639	1639	; systeminfo | Microsoft Learn systeminfo.htm
#define IDH_1640	1640	; takeown | Microsoft Learn takeown.htm
#define IDH_1647	1647	; tapicfg | Microsoft Learn tapicfg.htm
#define IDH_1641	1641	; tapicfg install | Microsoft Learn tapicfg-install.htm
#define IDH_1642	1642	; tapicfg makedefault | Microsoft Learn tapicfg-makedefault.htm
#define IDH_1643	1643	; tapicfg publishscp | Microsoft Learn tapicfg-publishscp.htm
#define IDH_1644	1644	; tapicfg remove | Microsoft Learn tapicfg-remove.htm
#define IDH_1645	1645	; tapicfg removescp | Microsoft Learn tapicfg-removescp.htm
#define IDH_1646	1646	; tapicfg show | Microsoft Learn tapicfg-show.htm
#define IDH_1648	1648	; taskkill | Microsoft Learn taskkill.htm
#define IDH_1649	1649	; tasklist | Microsoft Learn tasklist.htm
#define IDH_1650	1650	; tcmsetup | Microsoft Learn tcmsetup.htm
#define IDH_1659	1659	; telnet | Microsoft Learn telnet.htm
#define IDH_1651	1651	; telnet close | Microsoft Learn telnet-close.htm
#define IDH_1652	1652	; telnet display | Microsoft Learn telnet-display.htm
#define IDH_1653	1653	; telnet open | Microsoft Learn telnet-open.htm
#define IDH_1654	1654	; telnet quit | Microsoft Learn telnet-quit.htm
#define IDH_1655	1655	; telnet send | Microsoft Learn telnet-send.htm
#define IDH_1656	1656	; telnet set | Microsoft Learn telnet-set.htm
#define IDH_1657	1657	; telnet status | Microsoft Learn telnet-status.htm
#define IDH_1658	1658	; telnet unset | Microsoft Learn telnet-unset.htm
#define IDH_1660	1660	; tftp | Microsoft Learn tftp.htm
#define IDH_1661	1661	; time | Microsoft Learn time.htm
#define IDH_1662	1662	; timeout | Microsoft Learn timeout.htm
#define IDH_1663	1663	; title | Microsoft Learn title.htm
#define IDH_1664	1664	; tlntadmn | Microsoft Learn tlntadmn.htm
#define IDH_1665	1665	; tpmtool | Microsoft Learn tpmtool.htm
#define IDH_1666	1666	; tpmvscmgr | Microsoft Learn tpmvscmgr.htm
#define IDH_1667	1667	; tracerpt | Microsoft Learn tracerpt.htm
#define IDH_1668	1668	; tracert | Microsoft Learn tracert.htm
#define IDH_1669	1669	; tree | Microsoft Learn tree.htm
#define IDH_1670	1670	; tscon | Microsoft Learn tscon.htm
#define IDH_1671	1671	; tsdiscon | Microsoft Learn tsdiscon.htm
#define IDH_1672	1672	; tsecimp | Microsoft Learn tsecimp.htm
#define IDH_1673	1673	; tskill | Microsoft Learn tskill.htm
#define IDH_1674	1674	; tsprof | Microsoft Learn tsprof.htm
#define IDH_1676	1676	; typeperf | Microsoft Learn typeperf.htm
#define IDH_1677	1677	; tzutil | Microsoft Learn tzutil.htm
#define IDH_1678	1678	; unexpose | Microsoft Learn unexpose.htm
#define IDH_1679	1679	; uniqueid | Microsoft Learn uniqueid.htm
#define IDH_1680	1680	; unlodctr | Microsoft Learn unlodctr.htm
#define IDH_1790	1790	; Update-ServerFiles | Microsoft Learn wdsutil-update-serverfiles.htm
#define IDH_1681	1681	; ver | Microsoft Learn ver.htm
#define IDH_1682	1682	; verifier | Microsoft Learn verifier.htm
#define IDH_1684	1684	; vol | Microsoft Learn vol.htm
#define IDH_1689	1689	; vssadmin | Microsoft Learn vssadmin.htm
#define IDH_1685	1685	; vssadmin delete shadows | Microsoft Learn vssadmin-delete-shadows.htm
#define IDH_1686	1686	; vssadmin list shadows | Microsoft Learn vssadmin-list-shadows.htm
#define IDH_1687	1687	; vssadmin list writers | Microsoft Learn vssadmin-list-writers.htm
#define IDH_1688	1688	; vssadmin resize shadowstorage | Microsoft Learn vssadmin-resize-shadowstorage.htm
#define IDH_1690	1690	; waitfor | Microsoft Learn waitfor.htm
#define IDH_1706	1706	; wbadmin | Microsoft Learn wbadmin.htm
#define IDH_1691	1691	; wbadmin delete catalog | Microsoft Learn wbadmin-delete-catalog.htm
#define IDH_1692	1692	; wbadmin delete systemstatebackup | Microsoft Learn wbadmin-delete-systemstatebackup.htm
#define IDH_1693	1693	; wbadmin disable backup | Microsoft Learn wbadmin-disable-backup.htm
#define IDH_1694	1694	; wbadmin enable backup | Microsoft Learn wbadmin-enable-backup.htm
#define IDH_1695	1695	; wbadmin get disks | Microsoft Learn wbadmin-get-disks.htm
#define IDH_1696	1696	; wbadmin get items | Microsoft Learn wbadmin-get-items.htm
#define IDH_1697	1697	; wbadmin get status | Microsoft Learn wbadmin-get-status.htm
#define IDH_1698	1698	; wbadmin get versions | Microsoft Learn wbadmin-get-versions.htm
#define IDH_1699	1699	; wbadmin restore catalog | Microsoft Learn wbadmin-restore-catalog.htm
#define IDH_1700	1700	; wbadmin start backup | Microsoft Learn wbadmin-start-backup.htm
#define IDH_1701	1701	; wbadmin start recovery | Microsoft Learn wbadmin-start-recovery.htm
#define IDH_1702	1702	; wbadmin start sysrecovery | Microsoft Learn wbadmin-start-sysrecovery.htm
#define IDH_1703	1703	; wbadmin start systemstatebackup | Microsoft Learn wbadmin-start-systemstatebackup.htm
#define IDH_1704	1704	; wbadmin start systemstaterecovery | Microsoft Learn wbadmin-start-systemstaterecovery.htm
#define IDH_1705	1705	; wbadmin stop job | Microsoft Learn wbadmin-stop-job.htm
#define IDH_1792	1792	; wdsutil | Microsoft Learn wdsutil.htm
#define IDH_1718	1718	; wdsutil add | Microsoft Learn wdsutil-add.htm
#define IDH_1708	1708	; wdsutil add-device | Microsoft Learn wdsutil-add-device.htm
#define IDH_1709	1709	; wdsutil add-drivergroup | Microsoft Learn wdsutil-add-drivergroup.htm
#define IDH_1711	1711	; wdsutil add-drivergrouppackage | Microsoft Learn wdsutil-add-drivergrouppackage.htm
#define IDH_1712	1712	; wdsutil add-drivergrouppackages | Microsoft Learn wdsutil-add-drivergrouppackages.htm
#define IDH_1714	1714	; wdsutil add-image | Microsoft Learn wdsutil-add-image.htm
#define IDH_1715	1715	; wdsutil add-imagedriverpackage | Microsoft Learn wdsutil-add-imagedriverpackage.htm
#define IDH_1716	1716	; wdsutil add-imagedriverpackages | Microsoft Learn wdsutil-add-imagedriverpackages.htm
#define IDH_1717	1717	; wdsutil add-imagegroup | Microsoft Learn wdsutil-add-imagegroup.htm
#define IDH_1733	1733	; wdsutil alldevices | Microsoft Learn wdsutil-get-alldevices.htm
#define IDH_1734	1734	; wdsutil alldrivergroups | Microsoft Learn wdsutil-get-alldrivergroups.htm
#define IDH_1736	1736	; wdsutil allimagegroups | Microsoft Learn wdsutil-get-allimagegroups.htm
#define IDH_1719	1719	; wdsutil approve-autoadddevices | Microsoft Learn wdsutil-approve-autoadddevices.htm
#define IDH_1723	1723	; wdsutil copy | Microsoft Learn wdsutil-copy.htm
#define IDH_1722	1722	; wdsutil copy-image | Microsoft Learn wdsutil-copy-image.htm
#define IDH_1727	1727	; wdsutil disable | Microsoft Learn wdsutil-disable.htm
#define IDH_1726	1726	; wdsutil disable-transportserver | Microsoft Learn wdsutil-disable-transportserver.htm
#define IDH_1767	1767	; wdsutil driverpackages | Microsoft Learn wdsutil-remove-driverpackages.htm
#define IDH_1731	1731	; wdsutil enable | Microsoft Learn wdsutil-enable.htm
#define IDH_1729	1729	; wdsutil enable-server | Microsoft Learn wdsutil-enable-server.htm
#define IDH_1730	1730	; wdsutil enable-transportserver | Microsoft Learn wdsutil-enable-transportserver.htm
#define IDH_1753	1753	; wdsutil get | Microsoft Learn wdsutil-get.htm
#define IDH_1735	1735	; wdsutil get-alldriverpackages | Microsoft Learn wdsutil-get-alldriverpackages.htm
#define IDH_1737	1737	; wdsutil get-allimages | Microsoft Learn wdsutil-get-allimages.htm
#define IDH_1738	1738	; wdsutil get-allmulticasttransmissions | Microsoft Learn wdsutil-get-allmulticasttransmissions.htm
#define IDH_1739	1739	; wdsutil get-allnamespaces | Microsoft Learn wdsutil-get-allnamespaces.htm
#define IDH_1741	1741	; wdsutil get-autoadddevices | Microsoft Learn wdsutil-get-autoadddevices.htm
#define IDH_1742	1742	; wdsutil get-device | Microsoft Learn wdsutil-get-device.htm
#define IDH_1743	1743	; wdsutil get-drivergroup | Microsoft Learn wdsutil-get-drivergroup.htm
#define IDH_1745	1745	; wdsutil get-driverpackagefile | Microsoft Learn wdsutil-get-driverpackagefile.htm
#define IDH_1748	1748	; wdsutil get-imagegroup | Microsoft Learn wdsutil-get-imagegroup.htm
#define IDH_1749	1749	; wdsutil get-multicasttransmission | Microsoft Learn wdsutil-get-multicasttransmission.htm
#define IDH_1750	1750	; wdsutil get-namespace | Microsoft Learn wdsutil-get-namespace.htm
#define IDH_1751	1751	; wdsutil get-server | Microsoft Learn wdsutil-get-server.htm
#define IDH_1770	1770	; wdsutil multicasttransmission | Microsoft Learn wdsutil-remove-multicasttransmission.htm
#define IDH_1759	1759	; wdsutil new | Microsoft Learn wdsutil-new.htm
#define IDH_1757	1757	; wdsutil new-multicasttransmission | Microsoft Learn wdsutil-new-multicasttransmission.htm
#define IDH_1758	1758	; wdsutil new-namespace | Microsoft Learn wdsutil-new-namespace.htm
#define IDH_1760	1760	; wdsutil progress | Microsoft Learn wdsutil-progress.htm
#define IDH_1772	1772	; wdsutil remove | Microsoft Learn wdsutil-remove.htm
#define IDH_1765	1765	; wdsutil remove-drivergrouppackages | Microsoft Learn wdsutil-remove-drivergrouppackages.htm
#define IDH_1766	1766	; wdsutil remove-driverpackage | Microsoft Learn wdsutil-remove-driverpackage.htm
#define IDH_1769	1769	; wdsutil remove-imagegroup | Microsoft Learn wdsutil-remove-imagegroup.htm
#define IDH_1771	1771	; wdsutil remove-namespace | Microsoft Learn wdsutil-remove-namespace.htm
#define IDH_1773	1773	; wdsutil replace-image | Microsoft Learn wdsutil-replace-image.htm
#define IDH_1774	1774	; wdsutil set-device | Microsoft Learn wdsutil-set-device.htm
#define IDH_1778	1778	; wdsutil set-image | Microsoft Learn wdsutil-set-image.htm
#define IDH_1780	1780	; wdsutil set-server | Microsoft Learn wdsutil-set-server.htm
#define IDH_1781	1781	; wdsutil set-transportserver | Microsoft Learn wdsutil-set-transportserver.htm
#define IDH_1783	1783	; wdsutil start-multicasttransmission | Microsoft Learn wdsutil-start-multicasttransmission.htm
#define IDH_1784	1784	; wdsutil start-namespace | Microsoft Learn wdsutil-start-namespace.htm
#define IDH_1785	1785	; wdsutil start-server | Microsoft Learn wdsutil-start-server.htm
#define IDH_1752	1752	; wdsutil transportserver | Microsoft Learn wdsutil-get-transportserver.htm
#define IDH_1789	1789	; wdsutil uninitialize-server | Microsoft Learn wdsutil-uninitialize-server.htm
#define IDH_1754	1754	; wdsutil 初始化-服务器 | Microsoft Learn wdsutil-initialize-server.htm
#define IDH_1732	1732	; wdsutil 导出-映像 | Microsoft Learn wdsutil-export-image.htm
#define IDH_1728	1728	; wdsutil 断开连接-客户端 | Microsoft Learn wdsutil-disconnect-client.htm
#define IDH_1746	1746	; wdsutil 获取图像 | Microsoft Learn wdsutil-get-image.htm
#define IDH_1725	1725	; wdsutil 禁用-服务器 | Microsoft Learn wdsutil-disable-server.htm
#define IDH_1761	1761	; wdsutil 拒绝-autoadddevices | Microsoft Learn wdsutil-reject-autoadddevices.htm
#define IDH_1786	1786	; wdsutil 开始-transportserver | Microsoft Learn wdsutil-start-transportserver.htm
#define IDH_1724	1724	; wdsutil 删除-autoadddevices | Microsoft Learn wdsutil-delete-autoadddevices.htm
#define IDH_1768	1768	; wdsutil 删除-图像 | Microsoft Learn wdsutil-remove-image.htm
#define IDH_1779	1779	; wdsutil 设置-imagegroup | Microsoft Learn wdsutil-set-imagegroup.htm
#define IDH_1788	1788	; wdsutil 停止-transportserver | Microsoft Learn wdsutil-stop-transportserver.htm
#define IDH_1787	1787	; wdsutil 停止-服务器 | Microsoft Learn wdsutil-stop-server.htm
#define IDH_1707	1707	; wdsutil 外接程序 alldriverpackages | Microsoft Learn wdsutil-add-alldriverpackages.htm
#define IDH_1793	1793	; wecutil | Microsoft Learn wecutil.htm
#define IDH_1794	1794	; wevtutil | Microsoft Learn wevtutil.htm
#define IDH_1795	1795	; where | Microsoft Learn where.htm
#define IDH_1796	1796	; whoami | Microsoft Learn whoami.htm
#define IDH_1797	1797	; Windows 命令 | Microsoft Learn windows-commands.htm
#define IDH_1799	1799	; winnt32 | Microsoft Learn winnt32.htm
#define IDH_1798	1798	; winnt | Microsoft Learn winnt.htm
#define IDH_1800	1800	; winpop | Microsoft Learn winpop.htm
#define IDH_1801	1801	; winrs | Microsoft Learn winrs.htm
#define IDH_1802	1802	; winsat mem | Microsoft Learn winsat-mem.htm
#define IDH_1803	1803	; winsat mfmedia | Microsoft Learn winsat-mfmedia.htm
#define IDH_1804	1804	; wmic | Microsoft Learn wmic.htm
#define IDH_1805	1805	; writer | Microsoft Learn writer.htm
#define IDH_1806	1806	; wscript | Microsoft Learn wscript.htm
#define IDH_1807	1807	; xcopy | Microsoft Learn xcopy.htm
#define IDH_1246	1246	; 编辑 | Microsoft Learn edit.htm
#define IDH_1533	1533	; 查询进程 | Microsoft Learn query-process.htm
#define IDH_1537	1537	; 查询命令 | Microsoft Learn query.htm
#define IDH_1518	1518	; 打印命令行工具参考 | Microsoft Learn print-command-reference.htm
#define IDH_1346	1346	; 导入磁盘hadow | Microsoft Learn import.htm
#define IDH_1348	1348	; 非活跃 | Microsoft Learn inactive.htm
#define IDH_1010	1010	; 附加 vdisk | Microsoft Learn attach-vdisk.htm
#define IDH_1268	1268	; 干酪 | Microsoft Learn fondue.htm
#define IDH_1437	1437	; 更多 | Microsoft Learn more.htm
#define IDH_1171	1171	; 更改 | Microsoft Learn change.htm
#define IDH_1544	1544	; 恢复 (DiskPart)  | Microsoft Learn recover_1.htm
#define IDH_1000	1000	; 活动 | Microsoft Learn active.htm
#define IDH_1247	1247	; 结束备份 | Microsoft Learn end-backup.htm
#define IDH_1675	1675	; 类型 | Microsoft Learn type.htm
#define IDH_1491	1491	; 联机 | Microsoft Learn online.htm
#define IDH_1578	1578	; 路由 | Microsoft Learn route_ws2008.htm
#define IDH_1189	1189	; 命令行语法项 | Microsoft Learn command-line-syntax-key.htm
#define IDH_1563	1563	; 删除 | Microsoft Learn remove.htm
#define IDH_1618	1618	; 设置上下文 | Microsoft Learn set-context.htm
#define IDH_1782	1782	; 使用 set 命令 | Microsoft Learn wdsutil-set.htm
#define IDH_1791	1791	; 使用 verbose 命令 | Microsoft Learn wdsutil-verbose.htm
#define IDH_1631	1631	; 缩减 | Microsoft Learn shrink.htm
#define IDH_1617	1617	; 网络文件系统服务 (NFS) 命令行工具 | Microsoft Learn services-for-network-file-system-command-reference.htm
#define IDH_1225	1225	; 详细信息 | Microsoft Learn detail.htm
#define IDH_1567	1567	; 修复 | Microsoft Learn repair.htm
#define IDH_1430	1430	; 掩码 | Microsoft Learn mask.htm
#define IDH_1683	1683	; 验证 | Microsoft Learn verify.htm
#define IDH_1440	1440	; 移动 | Microsoft Learn move.htm
#define IDH_1562	1562	; 远程桌面服务 (终端服务) 命令行工具参考 | Microsoft Learn remote-desktop-services-terminal-services-command-reference.htm
#define IDH_1269	1269	; 针对 | Microsoft Learn for.htm
#define IDH_1162	1162	; 中断 (卷影复制)  | Microsoft Learn break_2.htm
#define IDH_1565	1565	; 重命名 | Microsoft Learn rename.htm
#define IDH_1569	1569	; 重新扫描 | Microsoft Learn rescan.htm
#define IDH_1405	1405	; 注销 | Microsoft Learn logoff.htm
